version: "3"

networks:
  gitea:
    external: false

services:
  server:
    build: .
    container_name: new-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db
      - GITEA__database__NAME=${DBNAME}
      - GITEA__database__USER=${NAME}
      - GITEA__database__PASSWD=${PASS}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_USER=${NAME}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=${DBNAME}
    networks:
      - gitea
    volumes:
      - mysql-data:/var/lib/mysql

  datadog:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
      - DD_SITE=datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  mysql-data:
    driver: local
